### ISSUE TITLE
About amd R7-250 diplaycard cant use vulkan mode

### ISSUE THREAD

**Issue by ekang4887** [substring/os#22]
I have use the newest ver GA OS@2022.1,It said can use amd diplaycard's vulkan drives in ga.And I install a pcsx2,and use the vulkan mode,it doesn't work.When I use opengl mode,it can work .SO,I think the vulkan drives is not work on my AMD R7 250,but,I can use vulkan in windows10.and I can use vulkan mode at pcsx2 in batocera x86 Ver34.
IF have some way let me know I have install the right vulkan drives?Or what amd displaycard can use vulkan in groovyarcade,Thanks!!

**Comment by substring** [comment]
Hi,
there are already vulkan drivers shipped with the distro (amdvlk 2022.Q1.1-1), have you updated since ?
Now I have a number of questions:

- how did you install PCSX2 ? Self compiled ? pacman ? Using the retroarch core ?
- Is your OS up to date ?
- you may have some extra steps to configure vulkan, check https://wiki.archlinux.org/title/Vulkan

I myself haven't tried Vulkan

**Comment by ekang4887** [comment]
1：sudo pacman -S pcsx2
2:the lastest
3:I have try three kind of amd's vulkan drive,but,no use. can't open vulkan.Maybe my R7 250is too old, the driver is not suppot it.

**Comment by substring** [comment]
Are you at least using the amdgpu driver ?
